version: '3'

services:
  recipes-db:
    container_name: recipes_database
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
